%% Check for monotonic time support in 18+
try erlang:system_info(os_monotonic_time_source) of
    _ ->
        Define = [{d, new_time}],
        case lists:keysearch(erl_opts, 1, CONFIG) of
            {value, {erl_opts, Opts}} ->
                lists:keyreplace(erl_opts, 1, CONFIG, {erl_opts, Opts ++ Define});
            false ->
                CONFIG ++ [{erl_opts, Define}]
        end
catch
    error:badarg ->
        CONFIG
end.
